version: '3'
services:

 coplayapp:
   depends_on:
     - coplayapi
   build:
      context: frontend/coplay
      dockerfile: Dockerfile
   image: jeret/coplay-app
   container_name: coplayapp
   restart: unless-stopped
   ports:
       - "80:3000"
   networks:
     - app-network
   environment:
    REACT_APP_API_ROOT: localhost
    REACT_APP_API_PORT: 3001

 coplayapi:
   depends_on:
     - db
   build:
      context: backend/api
      dockerfile: Dockerfile
   image: jeret/coplay-api
   container_name: coplayapi
   restart: unless-stopped
   env_file: .env
   ports:
       - "3001:3001"
   volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
   networks:
     - app-network
   #command: npm run db:init
   #command: npm start
   environment:
    NODE_ENV: production
    DB_HOST: db
    DB_PORT: $DB_PORT
    DB_USER: $DB_USER
    DB_PWD: $DB_PWD
    DB_NAME: $DB_NAME

 db:
   image: mysql:5.7
   container_name: db
   restart: unless-stopped
   env_file: .env
   ports:
     - "3306:3306"
   volumes:
     - db_data:/var/lib/mysql
   restart: always
   environment:
     MYSQL_ROOT_PASSWORD: $DB_PWD
     MYSQL_DATABASE: $DB_NAME
     MYSQL_USER: $DB_USER
     MYSQL_PASSWORD: $DB_PWD
   volumes:
     - dbdata:/data/db
   networks:
     - app-network


networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  node_modules:
