apiVersion: apps/v1
kind: Deployment
metadata:
  name: coplay-api
  #namespace is not really usefull is small project --> remove the line and it will be in default namespace
  #namespace: coplay
  labels:
    app: coplay-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coplay-api
  template:
    metadata:
      labels:
        app: coplay-api
    spec:
      containers:
      - name: coplayapi
        image: jeret/coplay-api
        ports:
        - containerPort: 3001
        env:
        - name: NODE_ENV
          value: "production"
        - name: DB_HOST
          value: "coplaydb-service"
        - name: DB_PORT
          value: "3306"
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: coplaydb-secret
              key: mysql-user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: coplaydb-secret
              key: mysql-pwd
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: coplaydb-secret
              key: mysql-root-pwd
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: coplaydb-secret
              key: mysql-database

---
apiVersion: v1
kind: Service
metadata:
  name: coplay-api-service
  #namespace is not really usefull is small project --> remove the line and it will be in default namespace
  #namespace: coplay
spec:
  selector:
    app: coplay-api
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
